// Auto-generated by Supabase - DO NOT EDIT MANUALLY
// Regenerate with: mcp__supabase__generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      anfragen: {
        Row: {
          created_at: string | null
          id: string
          mandant_id: string
          objekt_id: string
          status: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          mandant_id: string
          objekt_id: string
          status?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          mandant_id?: string
          objekt_id?: string
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "anfragen_mandant_id_fkey"
            columns: ["mandant_id"]
            isOneToOne: false
            referencedRelation: "mandanten"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "anfragen_objekt_id_fkey"
            columns: ["objekt_id"]
            isOneToOne: false
            referencedRelation: "objekte"
            referencedColumns: ["id"]
          },
        ]
      }
      ankaufsprofile: {
        Row: {
          assetklassen: string[] | null
          created_at: string | null
          id: string
          mandant_id: string
          max_volumen: number | null
          min_volumen: number | null
          name: string
          regionen: string | null
          rendite_min: number | null
          sonstiges: string | null
          updated_at: string | null
        }
        Insert: {
          assetklassen?: string[] | null
          created_at?: string | null
          id?: string
          mandant_id: string
          max_volumen?: number | null
          min_volumen?: number | null
          name: string
          regionen?: string | null
          rendite_min?: number | null
          sonstiges?: string | null
          updated_at?: string | null
        }
        Update: {
          assetklassen?: string[] | null
          created_at?: string | null
          id?: string
          mandant_id?: string
          max_volumen?: number | null
          min_volumen?: number | null
          name?: string
          regionen?: string | null
          rendite_min?: number | null
          sonstiges?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ankaufsprofile_mandant_id_fkey"
            columns: ["mandant_id"]
            isOneToOne: false
            referencedRelation: "mandanten"
            referencedColumns: ["id"]
          },
        ]
      }
      auswertungen: {
        Row: {
          berechnungen: Json | null
          created_at: string | null
          empfehlung: string | null
          empfehlung_begruendung: string | null
          empfehlung_chancen: Json | null
          empfehlung_fazit: string | null
          empfehlung_handlungsschritte: Json | null
          empfehlung_prioritaet: string | null
          empfehlung_risiken: Json | null
          erlaeuterungen: Json | null
          id: string
          mandant_id: string
          objekt_id: string
          pdf_url: string | null
          status: string | null
        }
        Insert: {
          berechnungen?: Json | null
          created_at?: string | null
          empfehlung?: string | null
          empfehlung_begruendung?: string | null
          empfehlung_chancen?: Json | null
          empfehlung_fazit?: string | null
          empfehlung_handlungsschritte?: Json | null
          empfehlung_prioritaet?: string | null
          empfehlung_risiken?: Json | null
          erlaeuterungen?: Json | null
          id?: string
          mandant_id: string
          objekt_id: string
          pdf_url?: string | null
          status?: string | null
        }
        Update: {
          berechnungen?: Json | null
          created_at?: string | null
          empfehlung?: string | null
          empfehlung_begruendung?: string | null
          empfehlung_chancen?: Json | null
          empfehlung_fazit?: string | null
          empfehlung_handlungsschritte?: Json | null
          empfehlung_prioritaet?: string | null
          empfehlung_risiken?: Json | null
          erlaeuterungen?: Json | null
          id?: string
          mandant_id?: string
          objekt_id?: string
          pdf_url?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "auswertungen_mandant_id_fkey"
            columns: ["mandant_id"]
            isOneToOne: false
            referencedRelation: "mandanten"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auswertungen_objekt_id_fkey"
            columns: ["objekt_id"]
            isOneToOne: false
            referencedRelation: "objekte"
            referencedColumns: ["id"]
          },
        ]
      }
      einheiten: {
        Row: {
          created_at: string | null
          flaeche: number | null
          id: string
          kaltmiete: number | null
          letzte_mieterhoehung: string | null
          mietvertragsart: string | null
          nutzung: string
          objekt_id: string
          position: number
          updated_at: string | null
          vergleichsmiete: number | null
        }
        Insert: {
          created_at?: string | null
          flaeche?: number | null
          id?: string
          kaltmiete?: number | null
          letzte_mieterhoehung?: string | null
          mietvertragsart?: string | null
          nutzung: string
          objekt_id: string
          position: number
          updated_at?: string | null
          vergleichsmiete?: number | null
        }
        Update: {
          created_at?: string | null
          flaeche?: number | null
          id?: string
          kaltmiete?: number | null
          letzte_mieterhoehung?: string | null
          mietvertragsart?: string | null
          nutzung?: string
          objekt_id?: string
          position?: number
          updated_at?: string | null
          vergleichsmiete?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "einheiten_objekt_id_fkey"
            columns: ["objekt_id"]
            isOneToOne: false
            referencedRelation: "objekte"
            referencedColumns: ["id"]
          },
        ]
      }
      mandanten: {
        Row: {
          ansprechpartner: string | null
          created_at: string | null
          email: string
          id: string
          kontaktart: string | null
          land: string | null
          name: string
          ort: string | null
          plz: string | null
          position: string | null
          strasse: string | null
          telefon: string | null
          updated_at: string | null
        }
        Insert: {
          ansprechpartner?: string | null
          created_at?: string | null
          email: string
          id?: string
          kontaktart?: string | null
          land?: string | null
          name: string
          ort?: string | null
          plz?: string | null
          position?: string | null
          strasse?: string | null
          telefon?: string | null
          updated_at?: string | null
        }
        Update: {
          ansprechpartner?: string | null
          created_at?: string | null
          email?: string
          id?: string
          kontaktart?: string | null
          land?: string | null
          name?: string
          ort?: string | null
          plz?: string | null
          position?: string | null
          strasse?: string | null
          telefon?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      objekte: {
        Row: {
          aufzug: boolean | null
          baujahr: number | null
          betriebskosten_nicht_umlage: number | null
          capex_geplant: string | null
          capex_geplant_betrag: number | null
          capex_vergangen: string | null
          created_at: string | null
          darlehensstand: number | null
          denkmalschutz: boolean | null
          eigenkapital_prozent: number | null
          gebaeude_wert: number | null
          gebaeudetyp: string | null
          geschosse: number | null
          gewerbe_sonderklauseln: boolean | null
          gewerbeeinheiten: number | null
          gewerbeflaeche: number | null
          grundstueck: number | null
          grundstueck_wert: number | null
          haltedauer: string | null
          heizungsart: string | null
          id: string
          instandhaltung: number | null
          investitionsbereitschaft: string | null
          kaufdatum: string | null
          kaufpreis: number
          kernsanierung_jahr: number | null
          leerstandsquote: number | null
          mandant_id: string
          mietpreisbindung: boolean | null
          milieuschutz: boolean | null
          modernisierungsstopp: boolean | null
          ort: string | null
          plz: string
          primaeres_ziel: string | null
          risikoprofil: string | null
          ruecklagen: number | null
          sozialbindung: boolean | null
          strasse: string
          tilgung: number | null
          umwandlungsverbot: boolean | null
          updated_at: string | null
          verwaltung: number | null
          weg_aufgeteilt: boolean | null
          weg_geplant: boolean | null
          wohneinheiten: number | null
          wohnflaeche: number | null
          zinssatz: number | null
        }
        Insert: {
          aufzug?: boolean | null
          baujahr?: number | null
          betriebskosten_nicht_umlage?: number | null
          capex_geplant?: string | null
          capex_geplant_betrag?: number | null
          capex_vergangen?: string | null
          created_at?: string | null
          darlehensstand?: number | null
          denkmalschutz?: boolean | null
          eigenkapital_prozent?: number | null
          gebaeude_wert?: number | null
          gebaeudetyp?: string | null
          geschosse?: number | null
          gewerbe_sonderklauseln?: boolean | null
          gewerbeeinheiten?: number | null
          gewerbeflaeche?: number | null
          grundstueck?: number | null
          grundstueck_wert?: number | null
          haltedauer?: string | null
          heizungsart?: string | null
          id?: string
          instandhaltung?: number | null
          investitionsbereitschaft?: string | null
          kaufdatum?: string | null
          kaufpreis: number
          kernsanierung_jahr?: number | null
          leerstandsquote?: number | null
          mandant_id: string
          mietpreisbindung?: boolean | null
          milieuschutz?: boolean | null
          modernisierungsstopp?: boolean | null
          ort?: string | null
          plz: string
          primaeres_ziel?: string | null
          risikoprofil?: string | null
          ruecklagen?: number | null
          sozialbindung?: boolean | null
          strasse: string
          tilgung?: number | null
          umwandlungsverbot?: boolean | null
          updated_at?: string | null
          verwaltung?: number | null
          weg_aufgeteilt?: boolean | null
          weg_geplant?: boolean | null
          wohneinheiten?: number | null
          wohnflaeche?: number | null
          zinssatz?: number | null
        }
        Update: {
          aufzug?: boolean | null
          baujahr?: number | null
          betriebskosten_nicht_umlage?: number | null
          capex_geplant?: string | null
          capex_geplant_betrag?: number | null
          capex_vergangen?: string | null
          created_at?: string | null
          darlehensstand?: number | null
          denkmalschutz?: boolean | null
          eigenkapital_prozent?: number | null
          gebaeude_wert?: number | null
          gebaeudetyp?: string | null
          geschosse?: number | null
          gewerbe_sonderklauseln?: boolean | null
          gewerbeeinheiten?: number | null
          gewerbeflaeche?: number | null
          grundstueck?: number | null
          grundstueck_wert?: number | null
          haltedauer?: string | null
          heizungsart?: string | null
          id?: string
          instandhaltung?: number | null
          investitionsbereitschaft?: string | null
          kaufdatum?: string | null
          kaufpreis?: number
          kernsanierung_jahr?: number | null
          leerstandsquote?: number | null
          mandant_id?: string
          mietpreisbindung?: boolean | null
          milieuschutz?: boolean | null
          modernisierungsstopp?: boolean | null
          ort?: string | null
          plz?: string
          primaeres_ziel?: string | null
          risikoprofil?: string | null
          ruecklagen?: number | null
          sozialbindung?: boolean | null
          strasse?: string
          tilgung?: number | null
          umwandlungsverbot?: boolean | null
          updated_at?: string | null
          verwaltung?: number | null
          weg_aufgeteilt?: boolean | null
          weg_geplant?: boolean | null
          wohneinheiten?: number | null
          wohnflaeche?: number | null
          zinssatz?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "objekte_mandant_id_fkey"
            columns: ["mandant_id"]
            isOneToOne: false
            referencedRelation: "mandanten"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string | null
          email: string | null
          id: string
          mandant_id: string | null
          name: string | null
          role: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email?: string | null
          id: string
          mandant_id?: string | null
          name?: string | null
          role?: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string | null
          id?: string
          mandant_id?: string | null
          name?: string | null
          role?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_mandant_id_fkey"
            columns: ["mandant_id"]
            isOneToOne: false
            referencedRelation: "mandanten"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean }
      user_mandant_id: { Args: Record<PropertyKey, never>; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never
